
spring:
  datasource: 
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: STUDENT
    password: student123456
    
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 1064437668070-udqalk37iuurur2469ieu1v9k02nc4v0.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - openid
           - profile
           - email     
           
